name: Deploy EMR Serverless App

on:
  workflow_dispatch:
      inputs:
        ref:
          description: "Git ref to deploy (branch or tag)"
          required: true
          default: "master"  # or any default branch or tag

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Make deploy script executable
        run: chmod +x ./deploy_prod.sh

      - name: Run deploy script
        run: ./deploy_prod.sh